CREATE SEQUENCE IF NOT EXISTS user_seq START 1;
CREATE SEQUENCE IF NOT EXISTS borrower_seq START 1;
CREATE SEQUENCE IF NOT EXISTS equipment_seq START 1;
CREATE SEQUENCE IF NOT EXISTS record_seq START 1;
CREATE SEQUENCE IF NOT EXISTS request_seq START 1;
CREATE SEQUENCE IF NOT EXISTS audit_seq START 1;
CREATE SEQUENCE IF NOT EXISTS adjustment_seq START 1;
